import { Header } from "@/app/(authenticated)/_navigation/header";
import { Sidebar } from "@/app/(authenticated)/_navigation/sidebar/components/sidebar";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import "./globals.css";

export const metadata: Metadata = {
  title: "Ticket Bounty",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header />
          <NuqsAdapter>
            <div className="flex h-screen overflow-hidden border-collapse">
              <Sidebar />
              <main className="min-h-screen flex-1 bg-secondary/20 flex flex-col py-24 px-8 overflow-y-auto overflow-x-hidden">
                {children}
              </main>
            </div>
          </NuqsAdapter>
          <Toaster expand />
        </ThemeProvider>
      </body>
    </html>
  );
}
